### ISSUE TITLE
connect fails when electrum fails on start

### ISSUE THREAD

**Issue by roeierez** [breez/breez-sdk-liquid#455]
This happens because chain service is initialized as part of connect and attempt to get the tip using electrum only to initialize ElectrumClient with the right tip.
Since our chain service re-subscribe to block headers when needed perhaps we can initialize it with 0 as tip and count on the fact it will recover in the background (sync is called immediately in the background and every some interval).

**Comment by ok300** [comment]
> we can initialize it with 0 as tip and count on the fact it will recover in the background (sync is called immediately in the background and every some interval).

Unfortuantely `sync` only synchronizes the LWK state, not our chain services. LWK internally uses its own separate ElectrumClient. So calls to `sync` will not help recover our chain service ElectrumClient.

**Comment by ok300** [comment]
While investigating I realised I'm not sure about the nature of the error.

@hydra-yse said he saw the error
```
Error: Made one or multiple attempts, all errored:
        - unexpected end of file
```
in a log, but it didn't interrupt our `connect` (correct @hydra-yse ?).

The error pointed out by @dangeross 
```
[ WARN electrum_client::client:192] call 'block_headers_subscribe_raw' failed after 2 attempts
```
is different. I got this frequently (sometimes every minute) when testing `drain`. The ElectrumClient itself logs it only as `WARN` and the original error message doesn't appear anywhere.

In addition, none of the above is what happens when there is a connectivity error to the Electrum server. In that case (e.g. using wrong ports for Electrum URLs) I'm getting
```
Error: Operation timed out (os error 60)
```
which immediately aborts `connect`. This is a different message and behavior from any of the above.

The only place where I found the original error message referenced was https://github.com/bitcoindevkit/rust-electrum-client/blob/0b97659b383554357fa55df1e9770e61b1d84ba4/src/types.rs#L351 It looks like an Electrum internal connection error.

---

If someone has a clearer idea of what's causing the original issue, please let me know.

**Comment by hydra-yse** [comment]
Apparently was an issue with Blockstream's electrum testnet instance. Has been fixed :+1:
