### ISSUE TITLE
Incoming offline payments using notifications

### ISSUE THREAD

**Issue by roeierez** [breez/breez-sdk-liquid#84]

**Comment by ok300** [comment]
Hey @tanx thanks for the question.

The LN -> Liquid swaps require one interaction from the receiver (in this case, the SDK) in order to complete. In fact, from the sender's point of view, the LN invoice will appear as pending until the receiver claims the funds, at which point it will appear as settled. For this to happen, the receiver has to be online (app has to be running) to detect there's an incoming payment and to claim the funds. This is why the mobile notifications are needed for offline receive, e.g. if the app is stopped or in the background.

**Comment by dangeross** [comment]
Closed by #433, #436
